Add sprite resources and implement movement
THis seems to be working as intended. However,
there is an error:

Exception in thread "AWT-EventQueue-0" java.lang
.NullPointerException: Cannot invoke
"Objects.Player.draw(java.awt.Graphics2D)"
because "this.player" is null
	at main.GamePanel.paintComponent(GamePanel.java:73)

I have no clue what's going on here